In [1]:
import pandas as pd

In [3]:
ventas = pd.read_csv("ventas.csv", parse_dates=["fecha"])
ventas.head()

       fecha store_id producto_id  unidades_vendidas
0 2024-01-01     S001     ESM-001                  2
1 2024-01-01     S001     ESM-002                  3
2 2024-01-01     S001     ESM-003                  2
3 2024-01-01     S001     ESM-004                  1
4 2024-01-01     S001     ESM-005                  1

In [12]:
demanda_prom = (ventas.groupby(["store_id", "producto_id"])["unidades_vendidas"].mean().reset_index(name="promedio de unidades vendidas"))
demanda_prom.head()

  store_id producto_id  promedio de unidades vendidas
0     S001     CEP-001                       1.177778
1     S001     CEP-002                       1.122222
2     S001     CEP-003                       1.155556
3     S001     CEP-004                       1.200000
4     S001     CEP-005                       1.311111

In [21]:
top_5_prom = (demanda_prom.groupby(["producto_id"])["unidades_vendidas"].min())

KeyError: 'Column not found: unidades_vendidas'